NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
SopinetChatBundle:
    resource: "@SopinetChatBundle/Resources/config/routing.yml"
    prefix:   /api/chat